Fix tests due to type changes in `fs-extra`
* this resolves error TS2352
* to mock `readFile` it needs to be cast to `unknown` before it is cast to the generic mock type `jest.Mock<any, any>` or any specific one (see: [StackOverflow](https://stackoverflow.com/questions/64758534/how-to-mock-a-specific-overload-of-a-function-with-jest-in-typescript))
* strangely this only occurs when jest is run with `--ci` and `--coverage` parameters, but not when run without parameters